Repository FppEpitech/Cryptography, pull requests merged in 2024-10, with the labels that each got.

#3 DOCS: Create the contributing md
  Contributing.md
Labels: documentation

#4 FEAT: Create the h option
  .gitignore
  my_pgp.py
Labels: enhancement

#9 FEAT: Create xor encryption
  Xor/Xor.py
  my_pgp
  unit_tests
Labels: enhancement

#11 FEAT: Create mirror workflow
  .github/workflows/mirror.yml
Labels: CI / CD

#13 FEAT: Create parsing system
  AES.py
  Error.py
  Mode.py
  PGP_AES.py
  PGP_XOR.py
  Parser.py
  RSA.py
  XOR.py
  my_pgp
Labels: enhancement

#17 FEAT: Create rsa generator
  AES.py
  Abstract/ACrypt.py
  PGP_AES.py
  PGP_XOR.py
  Parser.py
  RSA.py
  RSA/RSA.py
  XOR.py
  my_pgp
Labels: enhancement

#19 FEAT: Link Xor with the parsing
  Parser.py
  XOR.py
  Xor/Xor.py
  my_pgp
  unit_tests
Labels: enhancement

#22 FIX: Little endian
  Aes/AES.py
  unit_tests
Labels: bug

#24 FIX: Check key validity before get message
  Parser.py
Labels: bug

#26 FIX: Rsa generation
  Parser.py
  RSA/RSA.py
  unit_tests
Labels: bug

#29 FEAT: Implement rsa
  PGP_AES/PGP_AES.py
  Parser.py
  RSA/RSA.py
  my_pgp
Labels: enhancement

#32 feat(PGP): Create different parsing for PGP_AES and PGP_XOR
  Parser.py
Labels: enhancement

#33 FEAT: Implement pgp aes
  PGP_AES/PGP_AES.py
  Parser.py
  my_pgp
Labels: enhancement

#34 FEAT: Implement pgp xor
  PGP_XOR.py
  PGP_XOR/PGP_XOR.py
  RSA/RSA.py
  my_pgp
  unit_tests
Labels: enhancement
